create table if not exists public.quinte_supports (
  id bigint generated by default as identity primary key,
  race_date date not null,
  meeting_number integer not null,
  race_number integer not null,
  hippodrome text,
  discipline text,
  field_size integer,
  pmu_bet_code text not null default 'E_QUINTE_PLUS',
  is_evaluable boolean not null default true,
  exclusion_reason text,
  source text not null default 'PMU',
  created_at timestamptz not null default now(),
  unique (race_date, meeting_number, race_number)
);

alter table public.quinte_supports enable row level security;
revoke all on table public.quinte_supports from anon, authenticated;
grant select on table public.quinte_supports to anon, authenticated;
grant select, insert, update, delete on table public.quinte_supports to service_role;

drop policy if exists "Public read official Quinté supports" on public.quinte_supports;
create policy "Public read official Quinté supports"
  on public.quinte_supports for select
  to anon, authenticated
  using (true);

create table if not exists public.quinte_market_snapshots (
  id bigint generated by default as identity primary key,
  race_date date not null,
  meeting_number integer not null,
  race_number integer not null,
  horse_number integer not null,
  captured_at timestamptz not null default now(),
  odds numeric,
  market_probability numeric,
  source text not null default 'PMU_ONLINE',
  constraint quinte_market_probability_bounds check (market_probability is null or (market_probability >= 0 and market_probability <= 1)),
  constraint quinte_market_odds_bounds check (odds is null or odds > 1)
);

create index if not exists quinte_market_snapshots_race_time_idx
  on public.quinte_market_snapshots (race_date, meeting_number, race_number, captured_at desc);
create index if not exists quinte_market_snapshots_horse_time_idx
  on public.quinte_market_snapshots (race_date, meeting_number, race_number, horse_number, captured_at desc);

alter table public.quinte_market_snapshots enable row level security;
revoke all on table public.quinte_market_snapshots from anon, authenticated;
grant select on table public.quinte_market_snapshots to anon, authenticated;
grant select, insert, update, delete on table public.quinte_market_snapshots to service_role;

drop policy if exists "Public read Quinté market snapshots" on public.quinte_market_snapshots;
create policy "Public read Quinté market snapshots"
  on public.quinte_market_snapshots for select
  to anon, authenticated
  using (true);

insert into public.quinte_supports
(race_date, meeting_number, race_number, hippodrome, discipline, field_size, pmu_bet_code, is_evaluable, exclusion_reason, source)
values
('2026-06-01',1,4,'VICHY','ATTELE_VOLTE',13,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-02',1,1,'SAINT-CLOUD','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-03',1,1,'LAVAL','ATTELE_VOLTE',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-04',1,6,'ParisLongchamp','PLAT',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-05',1,4,'VINCENNES','ATTELE_AUTOSTART',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-06',1,4,'VINCENNES','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-07',1,3,'ParisLongchamp','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-08',1,8,'ANGERS','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-09',1,8,'COMPIEGNE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-10',1,6,'CAEN','ATTELE_VOLTE',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-11',1,6,'ParisLongchamp','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-12',1,4,'VINCENNES','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-13',1,4,'ENGHIEN','ATTELE_AUTOSTART',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-14',1,4,'CHANTILLY','PLAT',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-15',1,6,'ParisLongchamp','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-16',1,2,'NANTES','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-17',1,3,'AGEN LA GARENNE','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-18',1,7,'ParisLongchamp','PLAT',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-19',1,4,'VINCENNES','ATTELE_VOLTE',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-20',1,3,'COMPIEGNE','PLAT',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-21',1,9,'VINCENNES','ATTELE_VOLTE',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-22',1,8,'LYON-PARILLY','PLAT',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-23',1,8,'DIEPPE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-24',1,3,'CHERBOURG','ATTELE_VOLTE',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-25',5,4,'LAVAL','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-26',1,3,'ENGHIEN','ATTELE_AUTOSTART',13,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-27',1,2,'ENGHIEN','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-28',1,3,'SAINT-CLOUD','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-29',1,5,'CLAIREFONTAINE','HAIES',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-06-30',1,5,'VICHY','ATTELE_VOLTE',13,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-01',1,8,'ENGHIEN','ATTELE_AUTOSTART',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-02',1,7,'ParisLongchamp','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-03',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-04',1,4,'ENGHIEN','ATTELE_AUTOSTART',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-05',1,3,'SAINT-CLOUD','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-06',1,8,'LES SABLES D OLONNE','ATTELE_AUTOSTART',13,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-07',1,8,'CHANTILLY','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-08',1,5,'PORNICHET','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-09',1,8,'ENGHIEN','ATTELE_AUTOSTART',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-10',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-11',1,7,'ENGHIEN','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-12',1,3,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-13',1,8,'DIEPPE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-14',1,3,'ParisLongchamp','PLAT',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-15',1,8,'LISIEUX','ATTELE_AUTOSTART',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-16',1,8,'COMPIEGNE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-17',1,4,'CABOURG','ATTELE_VOLTE',13,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-18',1,4,'ENGHIEN','ATTELE_AUTOSTART',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-19',1,3,'CHANTILLY','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-20',1,8,'VICHY','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-21',1,8,'VICHY','PLAT',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-22',1,8,'ENGHIEN','ATTELE_VOLTE',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-23',1,8,'VICHY','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-24',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-25',1,4,'ENGHIEN','ATTELE_AUTOSTART',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-26',1,3,'MONT DE MARSAN','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-27',1,5,'CLAIREFONTAINE','STEEPLECHASE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-28',1,8,'COMPIEGNE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-29',1,1,'ENGHIEN','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-30',1,7,'DIEPPE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-07-31',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-01',1,3,'CLAIREFONTAINE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-02',1,3,'DEAUVILLE','PLAT',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-03',1,8,'CLAIREFONTAINE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-04',1,8,'DEAUVILLE','PLAT',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-05',1,5,'SAINT MALO','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-06',1,8,'ENGHIEN','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-07',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-08',1,3,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-09',1,3,'DEAUVILLE','PLAT',20,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-10',1,5,'CLAIREFONTAINE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-11',1,8,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-12',1,8,'ENGHIEN','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-13',1,8,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-14',1,4,'CABOURG','ATTELE_AUTOSTART',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-15',1,3,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-16',1,3,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-17',1,8,'CLAIREFONTAINE','HAIES',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-18',1,8,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-19',1,8,'LAVAL','ATTELE_VOLTE',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-20',1,8,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-21',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-22',1,3,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-23',1,3,'DEAUVILLE','PLAT',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-24',1,8,'VINCENNES','ATTELE_VOLTE',18,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-25',1,8,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-26',1,8,'CLAIREFONTAINE','STEEPLECHASE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-27',1,8,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-28',1,4,'CABOURG','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-29',1,4,'VINCENNES','ATTELE_VOLTE',13,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-08-30',1,3,'DEAUVILLE','PLAT',16,'E_QUINTE_PLUS',false,'Ex aequo dans l''arrivée validée','PMU'),
('2026-08-31',1,1,'SAINT-CLOUD','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-02',1,1,'LA CAPELLE','ATTELE_AUTOSTART',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-03',1,1,'ParisLongchamp','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-04',1,4,'VINCENNES','ATTELE_VOLTE',15,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-05',1,4,'VINCENNES','ATTELE_VOLTE',14,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-06',1,3,'ParisLongchamp','PLAT',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-07',1,1,'CRAON','ATTELE_VOLTE',16,'E_QUINTE_PLUS',true,null,'PMU'),
('2026-09-08',1,1,'AUTEUIL','HAIES',16,'E_QUINTE_PLUS',true,null,'PMU')
on conflict (race_date, meeting_number, race_number) do update set
  hippodrome=excluded.hippodrome,
  discipline=excluded.discipline,
  field_size=excluded.field_size,
  pmu_bet_code=excluded.pmu_bet_code,
  is_evaluable=excluded.is_evaluable,
  exclusion_reason=excluded.exclusion_reason,
  source=excluded.source;
